@jebeshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtZ3VsZ3VtODAwMDE1M3cwN3llaWJmamkiLCJ1c2VybmFtZSI6ImplYmVzaCIsImlhdCI6MTc2MjI2MDE2MSwiZXhwIjoxNzYyODY0OTYxfQ.pk2O5rv-y2yWnw7yiA5AQk3qHxR28M0yIlYon61l9xc
@sodaToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtaHlpMTZzcjAwMDA1M3Fjejlha21wNWoiLCJ1c2VybmFtZSI6Il9zb2RhIiwiaWF0IjoxNzYzMTAzMDQ4LCJleHAiOjE3NjM3MDc4NDh9.TKqzHnK-daGqVSXkOEZJPRnDBEUt_wLXzlxQwRWxjEo
@lemonToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtaHloM3BuazAwMDA1M25mYnB0OGozOHQiLCJ1c2VybmFtZSI6ImxlbW9uMjIiLCJpYXQiOjE3NjMxMDE0ODYsImV4cCI6MTc2MzcwNjI4Nn0.qr_Xi6RTrxhofFXbw39rSYWXdWynOHIJwgYTmPlthY0
@meopoToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtaHlpNW94ajAwMDA1M3ZlNXlsczQ4ZzUiLCJ1c2VybmFtZSI6Im1lb3BvNjciLCJpYXQiOjE3NjMxMDMyNTgsImV4cCI6MTc2MzcwODA1OH0.jU-UjxKfGxKWBOEsO6h6FWab0toBme42ura3MhQS58Y

### Create user jebesh
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation($input: CreateUserInput!) { createUser(createUserInput: $input) { user { name, username, email, id }, token } }",
  "variables": {
    "input": {
      "name": "Jebesh",
      "username": "jebesh",
      "email": "jebesh67@gmail.com",
      "password": "jebesh123",
      "confirmPassword": "jebesh123"
    }
  }
}

### Create user soda
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation($input: CreateUserInput!) { createUser(createUserInput: $input) { user { name, username, email, id }, token } }",
  "variables": {
    "input": {
      "name": "SodaPop",
      "username": "_soda",
      "email": "sodaeleven@gmail.com",
      "password": "soda123",
      "confirmPassword": "soda123"
    }
  }
}

### Create user lemon
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation($input: CreateUserInput!) { createUser(createUserInput: $input) { user { name, username, email, id }, token } }",
  "variables": {
    "input": {
      "name": "lemon",
      "username": "lemon22",
      "email": "lemon67@gmail.com",
      "password": "lemon123",
      "confirmPassword": "soda123"
    }
  }
}

### Create user meopo
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation($input: CreateUserInput!) { createUser(createUserInput: $input) { user { name, username, email, id }, token } }",
  "variables": {
    "input": {
      "name": "Meopo Jr",
      "username": "meopo67",
      "email": "meopo67@gmail.com",
      "password": "meopo123",
      "confirmPassword": "meopo123"
    }
  }
}


### Create new user with invaild email and password
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation($input: CreateUserInput!) { createUser(createUserInput: $input) { user { name, username, email, id }, token } }",
  "variables": {
    "input": {
      "name": "lalala",
      "username": "je3b@e sh",
      "email": "jebesh67mail.com",
      "password": "je es",
      "confirmPassword": ""
    }
  }
}

### Login with valid user
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation($input: LoginUserInput!) { loginUser(loginUserInput: $input) { user { name, username, id }, token } }",
  "variables": {
    "input": {
      "username": "jebesh11",
      "password": "jebesh123"
    }
  }
}


### Login with invalid username
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation($input: LoginUserInput!) { loginUser(loginUserInput: $input) { user { name, username, id }, token } }",
  "variables": {
    "input": {
      "username": "jebesh111",
      "password": "jebesh123"
    }
  }
}


### Login with wong password
POST http://localhost:5000/graphql
Content-Type: application/json

{
  "query": "mutation($input: LoginUserInput!) { loginUser(loginUserInput: $input) { user { name, username, id }, token } }",
  "variables": {
    "input": {
      "username": "jebesh",
      "password": "jebesh127773"
    }
  }
}

### logout
POST http://localhost:5000/graphql
Content-Type: application/json
Authorization: Bearer {{lemonToken}}

{
  "query": "query { logoutUser }"
}


### Check access
POST http://localhost:5000/graphql
Content-Type: application/json
Authorization: Bearer {{lemonToken}}

{
  "query": "query VerifyAccess { verifyAccess { data { accessGranted username message } } } "
}