import type { Metadata } from "next";
import "@/app/globals.css";
import { getTheme } from "@/core/utils/theme/util/server-only/getTheme.util";
import ClientAppShell from "@/core/wrappers/client-layout/ClientAppShell";
import { Theme } from "@/core/utils/theme/type/theme.type";
import ThemeProvider from "@/core/providers/theme/ThemeProvider";

export const metadata: Metadata = {
  title: "SocialMedia",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialTheme: Theme = await getTheme();
  
  return (
    <html lang="en">
      <body data-theme={ initialTheme }>
        <ThemeProvider initialTheme={ initialTheme }>
          <ClientAppShell>
            { children }
          </ClientAppShell>
        </ThemeProvider>
      </body>
    </html>
  );
}
