import type { Metadata } from "next";
import "@/app/globals.css";
import ThemeProvider from "@/common/providers/theme/ThemeProvider";
import clsx from "clsx";
import { getTheme } from "@/common/utils/theme/util/server-only/getTheme.util";
import { Navigation } from "@/components/navigation/Navigation";
import { Theme } from "@/common/utils/theme/types/theme.types";
import { ifTheme } from "@/common/utils/theme/util/theme.util";
import { ReactQueryProvider } from "@/common/providers/react-query/ReactQuery.provider";

export const metadata: Metadata = {
  title: "SocialMedia",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialTheme: Theme | undefined = await getTheme();
  
  return (
    <html lang="en">
      <body className={ clsx(
        ifTheme(initialTheme, "css-theme-dark", "css-theme-light"),
      ) }>
        <ReactQueryProvider>
          <ThemeProvider initialTheme={ initialTheme }>
            <div className={ "md:ml-15 pt-18 md:pt-6" }>
              { children }
            </div>
            <Navigation />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
