import type { Metadata } from "next";
import "@/app/globals.css";
import { getTheme } from "@/common/utils/theme/util/server-only/getTheme.util";
import ClientAppShell from "@/common/providers/client-layout/ClientAppShell";
import { Theme } from "@/common/utils/theme/types/theme.types";

export const metadata: Metadata = {
  title: "SocialMedia",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialTheme: Theme = await getTheme();
  
  return (
    <html lang="en">
      <body>
        <ClientAppShell initialTheme={ initialTheme }>{ children }</ClientAppShell>
      </body>
    </html>
  );
}
